language: php
php:
  - 7.1

git:
  depth: 1

branches:
  only:
    - master

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --dev --no-interaction

script:
  - vendor/bin/phpunit

after_script:
 - php vendor/bin/coveralls -v
