language: php
php:
  - 7.1
  - 7.2

git:
  depth: 1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --dev --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

after_script:
  - cp build/logs/clover.xml coverage.xml
  - travis_retry php vendor/bin/php-coveralls -v
  - bash <(curl -s https://codecov.io/bash)
